Ensure curl fails if response is 404

diff --git a/merge-pr b/merge-pr
--- a/merge-pr
+++ b/merge-pr
@@ -22,17 +22,22 @@ if [ $# != 2 ]; then
     echo 1>&2 "Usage: $0 <remote> <pr>"
     exit 1
 fi
-#BRANCH=$1
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
 REMOTE=$1
 PR=$2
 echo "Merging $PR from $REMOTE onto $BRANCH"
-#FETCH_URL=`git remote show $REMOTE|grep "Fetch URL"|cut -c14-`
 FETCH_URL=`git remote -v|grep $REMOTE|grep "fetch"|cut -f2|cut -d" " -f1`
 OWNER=`echo $FETCH_URL | cut -d: -f2 | cut -d/ -f1`
 REPO=`echo $FETCH_URL | cut -d/ -f2 | cut -d: -f1 | cut -d. -f1`
-PULL=`curl -s -n https://api.github.com/repos/$OWNER/$REPO/pulls/$PR`
-#PULL=`cat /tmp/out`
+set +e
+echo -n "Retrieving PR information from https://api.github.com/repos/$OWNER/$REPO/pulls/$PR..."
+PULL=`curl -s -n --fail https://api.github.com/repos/$OWNER/$REPO/pulls/$PR`
+if [ "${?}" -ne 0 ]; then
+  echo "Failed."
+  exit 2
+fi
+set -e
+
 MSG="Merge pull request #$PR from $(echo $PULL | jq -r .head.label)
 $(echo $PULL | jq -r .title)"
 echo "$MSG"
