Check git fetch result before running git merge

diff --git a/pr-merge b/pr-merge
--- a/pr-merge
+++ b/pr-merge
@@ -111,5 +111,9 @@ if [ -z "${NO_STOP_BEFORE_MERGE}" ] ; then
   echo -n "Continue..." && read _
 fi
 set -x
-git fetch "${REMOTE}" "pull/${PR_ID}/head"
+git fetch "${REMOTE}" "pull/${PR_ID}/head" 2>&1
+if [ "${?}" -ne 0 ]; then
+  echo "Failed to fetch PR"
+  exit 2
+fi
 git merge --no-ff -m "${MSG}" 'FETCH_HEAD'
